from pathlib import Path

from src.worktree.mounting.accessible import Object, Collection
from src.worktree.mounting.claim import Claim
from src.worktree.syncable.protocol import Syncable


class BaseSyncable(Syncable): # its not an ABC to avoid issues with multi-subclassing
    def sync(self): ...
    def commit(self): ...

    def ownership_claims(self) -> list[Claim]: ...

    def initialize_object(self, path: Path, obj: Object): ...
    def initialize_collection(self, path: Path, collection: Collection): ...

    def validate_object(self, path: Path, obj: Object): ...
    def validate_collection(self, path: Path, collection: Collection): ...

    def commit_object(self, path: Path, obj: Object): ...
    def commit_collection(self, path: Path, collection: Collection): ...